In [1]:
# Import des packages
from curl_cffi import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
# Ci dessous l'url permettant d'avoir les offres d'emploi sur linkedin :

url = "https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords=data&location=france&geoId=&trk=public_jobs_jobs-search-bar_search-submit&start=0"

1. Identifier les parametres important de l'url

Les paramètres importants de l'url sont après le "search?", on y voit la situation géographique (France), le trk montre que ca concerne les "public_jobs" et le start est a 0. Le paramètre keywords correspond à data, les jobs recherchés sont donc dans la data, le geoID n'est pas mentionné,

2. Requeter l'url , est ce que votre requete est acceptée ? Comment le savoir ?

In [6]:
html = requests.get(url)
print(f"Ma réponse est : {html.status_code}")

Ma réponse est : 200

La réponse est 200 donc ma requête est acceptée

3. Parser le contenu recupéré avec bs4 :

In [9]:
soup = BeautifulSoup(html.text, 'html.parser')
print(soup)

<!DOCTYPE html>

<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4407390052" data-impression-id="jobs-search-result-0" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="1" data-tracking-id="5mqVr0Ip3VH4iU8BvyzD1Q==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/crm-data-analysis-assistant-at-chlo%C3%A9-4407390052?position=1&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=5mqVr0Ip3VH4iU8BvyzD1Q%3D%3D">
<span class="sr-only">


        CRM &amp; Data Analysis Assistant


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/D4E0BAQExe3nhPsInsA/company-logo_100_100/company-logo_100_100/0/1705917414164/chloe_logo?e=2147483647&amp;v=beta&amp;t=R6SBM8d3nfBMshUwhPrH6J13iayhO5UHTveTbpy5Brc" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        CRM &amp; Data Analysis Assistant

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/chloe?trk=public_jobs_jserp-result_job-search-card-subtitle">
            Chloé
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Paris, Île-de-France, France
          </span>
<!-- -->
<time class="job-search-card__listdate" datetime="2026-06-20">


































      1 day ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4429565847" data-impression-id="jobs-search-result-1" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="2" data-tracking-id="zPQdlILedF7lCMdqW55o3g==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/warehouse-data-intern-at-bigblue-4429565847?position=2&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=zPQdlILedF7lCMdqW55o3g%3D%3D">
<span class="sr-only">


        Warehouse Data Intern


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/C4D0BAQGSpyNbH-thPQ/company-logo_100_100/company-logo_100_100/0/1676049185334/bigblue_co_logo?e=2147483647&amp;v=beta&amp;t=_g1kKUoEfWuq1APve0pyp9FDrGX7yoYaoqVxckmUM2k" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        Warehouse Data Intern

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/bigblue-co?trk=public_jobs_jserp-result_job-search-card-subtitle">
            Bigblue
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Paris, Île-de-France, France
          </span>
<!-- -->
<time class="job-search-card__listdate" datetime="2026-06-16">


































      5 days ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4430411742" data-impression-id="jobs-search-result-2" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="3" data-tracking-id="x8z5eNTwNwQORkGHUFhCZg==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/assistant-chef-de-projet-crm-h-f-at-fff-f%C3%A9d%C3%A9ration-fran%C3%A7aise-de-football-4430411742?position=3&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=x8z5eNTwNwQORkGHUFhCZg%3D%3D">
<span class="sr-only">


        Assistant Chef de Projet CRM H.F


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/C560BAQGvujzfspmFag/company-logo_100_100/company-logo_100_100/0/1630564216712/federation_fran_aise_de_football_logo?e=2147483647&amp;v=beta&amp;t=HVJRP52Bj9DKrXcofWy29VWajkiSXWCu8UyVbkyxuNk" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        Assistant Chef de Projet CRM H.F

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/federation-francaise-de-football?trk=public_jobs_jserp-result_job-search-card-subtitle">
            FFF - Fédération Française de Football
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Paris, Île-de-France, France
          </span>
<!-- -->
<time class="job-search-card__listdate" datetime="2026-06-18">


































      4 days ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4428239828" data-impression-id="jobs-search-result-3" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="4" data-tracking-id="XovjLzx1pJUy8WisKIRmhw==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/saint-laurent-data-scientist-intern-at-saint-laurent-4428239828?position=4&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=XovjLzx1pJUy8WisKIRmhw%3D%3D">
<span class="sr-only">


        SAINT LAURENT Data Scientist Intern


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/D4E0BAQEIaYaq3yae5w/company-logo_100_100/company-logo_100_100/0/1720618235437/yves_saint_laurent_logo?e=2147483647&amp;v=beta&amp;t=v1YWlH_mv8F5GfB3ZfcVHB9m93UMu3FTxs6QPMLJDwk" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        SAINT LAURENT Data Scientist Intern

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/yves-saint-laurent?trk=public_jobs_jserp-result_job-search-card-subtitle">
            Saint Laurent
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Paris, Île-de-France, France
          </span>
<div class="job-posting-benefits text-sm">
<icon class="job-posting-benefits__icon" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/3p1v0uhy7uq0cm5zdvzp4eo18" data-svg-class-name="job-posting-benefits__icon-svg"></icon>
<span class="job-posting-benefits__text">
          Actively Hiring
<!-- --> </span>
</div>
<time class="job-search-card__listdate" datetime="2026-06-19">


































      2 days ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4428529994" data-impression-id="jobs-search-result-4" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="5" data-tracking-id="hj6pLwSlMIClH/f/klk69g==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/junior-data-scientist-f-m-at-vinci-airports-4428529994?position=5&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=hj6pLwSlMIClH%2Ff%2Fklk69g%3D%3D">
<span class="sr-only">


        Junior Data Scientist (F/M)


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/C4D0BAQEcsOBpKCZXWQ/company-logo_100_100/company-logo_100_100/0/1631331915063?e=2147483647&amp;v=beta&amp;t=S_vN_K0F6w0qo8rV-my0eXwqeFljWneq-POEYE0dyyI" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        Junior Data Scientist (F/M)

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/vinci-airports?trk=public_jobs_jserp-result_job-search-card-subtitle">
            VINCI Airports
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Nanterre, Île-de-France, France
          </span>
<div class="job-posting-benefits text-sm">
<icon class="job-posting-benefits__icon" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/3p1v0uhy7uq0cm5zdvzp4eo18" data-svg-class-name="job-posting-benefits__icon-svg"></icon>
<span class="job-posting-benefits__text">
          Actively Hiring
<!-- --> </span>
</div>
<time class="job-search-card__listdate" datetime="2026-06-20">


































      1 day ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4426857264" data-impression-id="jobs-search-result-5" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="6" data-tracking-id="5u8EzCjrFoXQmyVZPjYnCQ==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/alternance-data-analyst-f-h-at-fondation-bouygues-telecom-4426857264?position=6&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=5u8EzCjrFoXQmyVZPjYnCQ%3D%3D">
<span class="sr-only">


        Alternance Data analyst F/H


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/C4E0BAQE3BLUMT9Z5iw/company-logo_100_100/company-logo_100_100/0/1644253117239/fondation_dentreprise_bouygues_telecom_logo?e=2147483647&amp;v=beta&amp;t=6Vh_YZ16HqiQNjenElxK3CSFOFfm5u222xmUQdjlARw" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        Alternance Data analyst F/H

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/fondation-d'entreprise-bouygues-telecom?trk=public_jobs_jserp-result_job-search-card-subtitle">
            Fondation Bouygues Telecom
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Issy-les-Moulineaux, Île-de-France, France
          </span>
<!-- -->
<time class="job-search-card__listdate" datetime="2026-06-16">


































      5 days ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4426827839" data-impression-id="jobs-search-result-6" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="7" data-tracking-id="8IfLRHf7LjSfpHIC1WflNQ==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/reporting-analyst-h-f-at-lagard%C3%A8re-travel-retail-4426827839?position=7&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=8IfLRHf7LjSfpHIC1WflNQ%3D%3D">
<span class="sr-only">


        Reporting analyst H/F


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/C4E0BAQFNG_HigwCthg/company-logo_100_100/company-logo_100_100/0/1656586788306/lagarderetravelretail_logo?e=2147483647&amp;v=beta&amp;t=3h8Hg2H4ptFYiurCMXrgmf0X1jhhHmy9lWlgEWG9onA" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        Reporting analyst H/F

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/lagarderetravelretail?trk=public_jobs_jserp-result_job-search-card-subtitle">
            Lagardère Travel Retail
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Levallois-Perret, Île-de-France, France
          </span>
<div class="job-posting-benefits text-sm">
<icon class="job-posting-benefits__icon" data-delayed-url="https://static.licdn.com/aero-v1/sc/h/3p1v0uhy7uq0cm5zdvzp4eo18" data-svg-class-name="job-posting-benefits__icon-svg"></icon>
<span class="job-posting-benefits__text">
          Actively Hiring
<!-- --> </span>
</div>
<time class="job-search-card__listdate" datetime="2026-06-16">


































      5 days ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4428465774" data-impression-id="jobs-search-result-7" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="8" data-tracking-id="86ohBue1t8sdm58lta/dkg==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/assistant-e-d%C3%A9veloppeur-data-at-olympique-de-marseille-4428465774?position=8&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=86ohBue1t8sdm58lta%2Fdkg%3D%3D">
<span class="sr-only">


        Assistant(e) Développeur Data


          </span>
</a>
<div class="search-entity-media">
<img alt="" class="artdeco-entity-image artdeco-entity-image--square-4" data-delayed-url="https://media.licdn.com/dms/image/v2/D4D0BAQGHDUrbsEFM5g/company-logo_100_100/B4DZ1uS.ojKIAQ-/0/1775671962814/sasp_olympique_de_marseille_logo?e=2147483647&amp;v=beta&amp;t=bgiBnFc72uEsD8L0s7slaPnYhRRLB5X8PBZMwBPYJbk" data-ghost-classes="artdeco-entity-image--ghost" data-ghost-url="https://static.licdn.com/aero-v1/sc/h/6puxblwmhnodu6fjircz4dn4h"/>
</div>
<div class="base-search-card__info">
<h3 class="base-search-card__title">

        Assistant(e) Développeur Data

          </h3>
<h4 class="base-search-card__subtitle">
<a class="hidden-nested-link" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_job-search-card-subtitle" data-tracking-will-navigate="" href="https://fr.linkedin.com/company/sasp-olympique-de-marseille?trk=public_jobs_jserp-result_job-search-card-subtitle">
            Olympique de Marseille
          </a>
</h4>
<!-- -->
<div class="base-search-card__metadata">
<span class="job-search-card__location">
            Marseille, Provence-Alpes-Côte d'Azur, France
          </span>
<!-- -->
<time class="job-search-card__listdate" datetime="2026-06-17">


































      5 days ago

          </time>
<!-- -->
</div>
</div>
<!-- -->
</div>
</li>
<li>
<div class="base-card relative w-full hover:no-underline focus:no-underline base-card--link base-search-card base-search-card--link job-search-card" data-column="1" data-entity-urn="urn:li:jobPosting:4426834474" data-impression-id="jobs-search-result-8" data-reference-id="S+T1cncx4WdEXl9FVEke6A==" data-row="9" data-tracking-id="CYRPOCUHrdRsB2RkAgxyBQ==">
<a class="base-card__full-link absolute top-0 right-0 bottom-0 left-0 p-0 z-[2] outline-offset-[4px]" data-tracking-client-ingraph="" data-tracking-control-name="public_jobs_jserp-result_search-card" data-tracking-will-navigate="" href="https://fr.linkedin.com/jobs/view/alternance-data-contr%C3%B4le-interne-power-bi-at-lacroix-4426834474?position=9&amp;pageNum=0&amp;refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&amp;trackingId=CYRPOCUHrdRsB2RkAgxyBQ%3D%3D">
<span class="sr-only">


        Alternance - Data &amp; Contrôle Interne (Power BI)


          </span>
</a>
<div class="search-entity-media">

4. Récuperer le titre de l'annonce, le nom de l'entreprise, localisation , lien du détail de l'offre et la date de l'offre :

In [18]:
# J'affiche le nombre de divs
divs = soup.find_all('div', class_='base-card')
print(f"Nombre de divs trouvés : {len(divs)}")

Nombre de divs trouvés : 10

In [ ]:
# J'affiche le texte le la première div

divs[0].text

'\n\n\n              \n        \n        CRM & Data Analysis Assistant\n      \n      \n          \n\n\n\n\n\n\n            \n        CRM & Data Analysis Assistant\n      \n          \n\n\n            Chloé\n          \n\n\n\n\n            Paris, Île-de-France, France\n          \n\n\n            \n\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n\n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n    \n\n      1 day ago\n  \n          \n\n\n\n\n'

In [22]:
# Je crée une variable pour stocker mon premier div

divn1 = divs[0]

In [33]:
# Je cherche a trouver le titre de l'offre 

job = divn1.find('h3', class_='base-search-card__title').get_text().strip()
print(f"Le premier job est : {job}")

Le premier job est : CRM & Data Analysis Assistant

In [61]:
# Maintenant je veux boucler pour recuperer tous les jobs

# Je récupère les jobs
for i in divs :
    job = i.find('h3', class_='base-search-card__title').get_text().strip()
    print(job)

# Je l'affiche en compréhension de liste et je le stocke dans une variable
boucle_job = [i.find('h3', class_='base-search-card__title').get_text().strip() for i in divs]

CRM & Data Analysis Assistant
Warehouse Data Intern
Assistant Chef de Projet CRM H.F
SAINT LAURENT Data Scientist Intern
Junior Data Scientist (F/M)
Alternance Data analyst F/H
Reporting analyst H/F
Assistant(e) Développeur Data
Alternance - Data & Contrôle Interne (Power BI)
Data Analyst Junior

In [46]:
# Maintenant je fais pareil pour le nom de l'entreprise 

# Je cherche a trouver le nom de l'entreprise

entreprise = divn1.find('h4', class_='base-search-card__subtitle').get_text().strip()
print(f"La premiere entreprise est : {entreprise}")

La premiere entreprise est : Chloé

In [60]:
# Maintenant je veux boucler pour recuperer toutes les entreprises

# Je récupère les entreprise
for i in divs :
    entreprise = i.find('h4', class_='base-search-card__subtitle').get_text().strip()
    print(entreprise)

# Je l'affiche en compréhension de liste et je le stocke dans une variable
boucle_entreprise = [i.find('h4', class_='base-search-card__subtitle').get_text().strip() for i in divs]

Chloé
Bigblue
FFF - Fédération Française de Football
Saint Laurent
VINCI Airports
Fondation Bouygues Telecom
Lagardère Travel Retail
Olympique de Marseille
LACROIX
Unlimitail

In [57]:
# Maintenant je fais pareil pour le lien de l'offre 

# Je cherche a trouver le lien de l'offre

offre = divn1.find('a')['href']
print(f"Le lien de la premiere offre est : {offre}")

Le lien de la premiere offre est : https://fr.linkedin.com/jobs/view/crm-data-analysis-assistant-at-chlo%C3%A9-4407390052?position=1&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=5mqVr0Ip3VH4iU8BvyzD1Q%3D%3D

In [62]:
# Maintenant je veux boucler pour recuperer touts les liens

# Je récupère les liens
for i in divs :
    lien = i.find('a')['href']
    print(lien)

# Je l'affiche en compréhension de liste et je le stocke dans une variable
boucle_lien = [i.find('a')['href'] for i in divs]

https://fr.linkedin.com/jobs/view/crm-data-analysis-assistant-at-chlo%C3%A9-4407390052?position=1&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=5mqVr0Ip3VH4iU8BvyzD1Q%3D%3D
https://fr.linkedin.com/jobs/view/warehouse-data-intern-at-bigblue-4429565847?position=2&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=zPQdlILedF7lCMdqW55o3g%3D%3D
https://fr.linkedin.com/jobs/view/assistant-chef-de-projet-crm-h-f-at-fff-f%C3%A9d%C3%A9ration-fran%C3%A7aise-de-football-4430411742?position=3&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=x8z5eNTwNwQORkGHUFhCZg%3D%3D
https://fr.linkedin.com/jobs/view/saint-laurent-data-scientist-intern-at-saint-laurent-4428239828?position=4&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=XovjLzx1pJUy8WisKIRmhw%3D%3D
https://fr.linkedin.com/jobs/view/junior-data-scientist-f-m-at-vinci-airports-4428529994?position=5&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=hj6pLwSlMIClH%2Ff%2Fklk69g%3D%3D
https://fr.linkedin.com/jobs/view/alternance-data-analyst-f-h-at-fondation-bouygues-telecom-4426857264?position=6&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=5u8EzCjrFoXQmyVZPjYnCQ%3D%3D
https://fr.linkedin.com/jobs/view/reporting-analyst-h-f-at-lagard%C3%A8re-travel-retail-4426827839?position=7&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=8IfLRHf7LjSfpHIC1WflNQ%3D%3D
https://fr.linkedin.com/jobs/view/assistant-e-d%C3%A9veloppeur-data-at-olympique-de-marseille-4428465774?position=8&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=86ohBue1t8sdm58lta%2Fdkg%3D%3D
https://fr.linkedin.com/jobs/view/alternance-data-contr%C3%B4le-interne-power-bi-at-lacroix-4426834474?position=9&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=CYRPOCUHrdRsB2RkAgxyBQ%3D%3D
https://fr.linkedin.com/jobs/view/data-analyst-junior-at-unlimitail-4424520259?position=10&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=ujKm%2Bv3v6N42d7czraPX8Q%3D%3D

In [59]:
# Maintenant je fais pareil pour la date de l'offre 

# Je cherche a trouver la date de l'offre

date = divn1.find('time')['datetime']
print(f"La date de la première offre est : {date}")

La date de la première offre est : 2026-06-20

In [63]:
# Maintenant je veux boucler pour recuperer toutes les dates

# Je récupère les dates
for i in divs :
    date = i.find('time')['datetime']
    print(date)

# Je l'affiche en compréhension de liste et je le stocke dans une variable
boucle_date = [i.find('time')['datetime'] for i in divs]

2026-06-20
2026-06-16
2026-06-18
2026-06-19
2026-06-20
2026-06-16
2026-06-16
2026-06-17
2026-06-16
2026-06-05

5. Stocker les datas récupérées dans un dataframe:

In [64]:
df_linkedin = pd.DataFrame({"jobs" : boucle_job,
              "entreprise" : boucle_entreprise,
              "lien" : boucle_lien,
              "date" : boucle_date})

df_linkedin

,jobs,entreprise,lien,date
0,CRM & Data Analysis Assistant,Chloé,https://fr.linkedin.com/jobs/view/crm-data-ana...,2026-06-20
1,Warehouse Data Intern,Bigblue,https://fr.linkedin.com/jobs/view/warehouse-da...,2026-06-16
2,Assistant Chef de Projet CRM H.F,FFF - Fédération Française de Football,https://fr.linkedin.com/jobs/view/assistant-ch...,2026-06-18
3,SAINT LAURENT Data Scientist Intern,Saint Laurent,https://fr.linkedin.com/jobs/view/saint-lauren...,2026-06-19
4,Junior Data Scientist (F/M),VINCI Airports,https://fr.linkedin.com/jobs/view/junior-data-...,2026-06-20
5,Alternance Data analyst F/H,Fondation Bouygues Telecom,https://fr.linkedin.com/jobs/view/alternance-d...,2026-06-16
6,Reporting analyst H/F,Lagardère Travel Retail,https://fr.linkedin.com/jobs/view/reporting-an...,2026-06-16
7,Assistant(e) Développeur Data,Olympique de Marseille,https://fr.linkedin.com/jobs/view/assistant-e-...,2026-06-17
8,Alternance - Data & Contrôle Interne (Power BI),LACROIX,https://fr.linkedin.com/jobs/view/alternance-d...,2026-06-16
9,Data Analyst Junior,Unlimitail,https://fr.linkedin.com/jobs/view/data-analyst...,2026-06-05

## Bonus 1 :

Nous souhaitons maintenant avoir les détails des différentes offres d'emploi.

\
Pour cela vous devez

- Recupérer l'id du job à partir de l'url récupéré (utiliser regex)


- Remplacer cette url à chaque fois par l'id du job
https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{id}


- Requeter l'url du detail de job et avoir le max d'info interessantes


\
Comment automatiser pour tous les job  (voir url comment faire varier la page)?

In [69]:
# J'affiche un lien :

lien1 = df_linkedin['lien'][0]

lien1

'https://fr.linkedin.com/jobs/view/crm-data-analysis-assistant-at-chlo%C3%A9-4407390052?position=1&pageNum=0&refId=S%2BT1cncx4WdEXl9FVEke6A%3D%3D&trackingId=5mqVr0Ip3VH4iU8BvyzD1Q%3D%3D'

In [78]:
# J'utilise regex pour recuperer l'id du job à partir de l'url

import re

id = re.search(r"\d{10}", lien1).group() # Je compte que l'id contient 10 chiffres donc j'utilise \d pour digit puis 10 pour les chiffres

id

'4407390052'

In [87]:
url_detail = f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{id}"
url_detail

'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4407390052'

In [99]:
# Je crée une fonction pour créer des liens avec l'id

def url_id(lien):
    id = re.search(r"\d{10}", lien).group()
    lien = f"https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/{id}"
    return lien

df_linkedin["info_id"] = df_linkedin['lien'].apply(url_id)

df_linkedin.head()

,jobs,entreprise,lien,date,info_id
0,CRM & Data Analysis Assistant,Chloé,https://fr.linkedin.com/jobs/view/crm-data-ana...,2026-06-20,https://www.linkedin.com/jobs-guest/jobs/api/j...
1,Warehouse Data Intern,Bigblue,https://fr.linkedin.com/jobs/view/warehouse-da...,2026-06-16,https://www.linkedin.com/jobs-guest/jobs/api/j...
2,Assistant Chef de Projet CRM H.F,FFF - Fédération Française de Football,https://fr.linkedin.com/jobs/view/assistant-ch...,2026-06-18,https://www.linkedin.com/jobs-guest/jobs/api/j...
3,SAINT LAURENT Data Scientist Intern,Saint Laurent,https://fr.linkedin.com/jobs/view/saint-lauren...,2026-06-19,https://www.linkedin.com/jobs-guest/jobs/api/j...
4,Junior Data Scientist (F/M),VINCI Airports,https://fr.linkedin.com/jobs/view/junior-data-...,2026-06-20,https://www.linkedin.com/jobs-guest/jobs/api/j...

In [102]:
df_linkedin['info_id'][2]

'https://www.linkedin.com/jobs-guest/jobs/api/jobPosting/4430411742'